service: default
runtime: nodejs16
instance_class: F1
automatic_scaling:
  max_instances: 1

handlers:
  - url: /_nuxt
    static_dir: .output/public/_nuxt
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: .output/public/\1
    upload: .output/public/.*\.(gif|png|jpg|ico|txt)$
    secure: always

  - url: /.*
    script: auto
    secure: always
